import re
import datetime

class SwiftCore:
    def __init__(self):
        self.version = "1.0.0"
        self.author = "Spawn.ai"
        # Gelişmiş dil şablonları
        self.languages = {
            "python": {
                "header": "# Generated by SwiftCore AI\nimport os, sys\n",
                "print": "print(f\"{msg}\")",
                "loop": "for i in range({n}):\n    {body}",
                "function": "def {name}({args}):\n    \"\"\"{doc}\"\"\"\n    {body}",
                "class": "class {name}:\n    def __init__(self):\n        pass"
            },
            "cpp": {
                "header": "// Generated by SwiftCore AI\n#include <iostream>\n#include <vector>\n\nusing namespace std;\n",
                "print": "cout << \"{msg}\" << endl;",
                "loop": "for(int i = 0; i < {n}; ++i) {{\n    {body}\n}}",
                "function": "{type} {name}({args}) {{\n    {body}\n    return {ret};\n}}",
                "class": "class {name} {{\npublic:\n    {name}() {{}}\n}};"
            }
        }

    def _intent_parser(self, prompt):
        """Doğal dili analiz ederek yapılandırılmış mantığa (IR) dönüştürür."""
        prompt = prompt.lower()
        ir = {"action": None, "params": {}}

        # Döngü Analizi (örn: 10 defa dön)
        loop_match = re.search(r'(\d+)\s*(defa|kere|times|iterations)', prompt)
        if loop_match:
            ir["action"] = "loop"
            ir["params"]["n"] = loop_match.group(1)

        # Fonksiyon Analizi (örn: 'topla' adında bir fonksiyon oluştur)
        func_match = re.search(r'(\w+)\s*(adında|isimli)?\s*fonksiyon', prompt)
        if func_match:
            ir["action"] = "function"
            ir["params"]["name"] = func_match.group(1)
            ir["params"]["args"] = "" # Opsiyonel geliştirilebilir

        # Yazdırma Analizi
        print_match = re.search(r'\"(.+?)\"|(.+?)\s*(yazdır|print)', prompt)
        if print_match:
            ir["params"]["msg"] = print_match.group(1) or print_match.group(2).strip()
            if not ir["action"]: ir["action"] = "print"

        return ir

    def generate(self, prompt, target="python"):
        """Mantığı koda dönüştüren ana motor."""
        ir = self._intent_parser(prompt)
        lang = self.languages.get(target.lower())
        
        if not lang:
            return f"Error: Language '{target}' not supported."

        output = lang["header"] + "\n"
        
        if ir["action"] == "print":
            output += lang["print"].format(msg=ir["params"].get("msg", "Hello from SwiftCore"))
        
        elif ir["action"] == "loop":
            inner_body = lang["print"].format(msg=ir["params"].get("msg", "Iteration active"))
            output += lang["loop"].format(n=ir["params"]["n"], body=inner_body)
            
        elif ir["action"] == "function":
            ret_val = "0" if target == "cpp" else "None"
            output += lang["function"].format(
                type="void", name=ir["params"]["name"], args="", 
                doc="Generated by SwiftCore", body=lang["print"].format(msg="Function Executed"),
                ret=ret_val
            )
            
        return output

# --- Örnek Başlatıcı ---
if __name__ == "__main__":
    core = SwiftCore()
    cmd = "10 defa 'Sistem Kontrol Ediliyor' yazdır"
    
    print(">>> SWIFTCORE GENERATION (C++) <<<\n")
    print(core.generate(cmd, "cpp"))